require('dotenv').config();
const mongoose = require('mongoose');
const Audience = require('../models/audienceRange');

// Array of audience age ranges to seed\const 
ranges = 
[
  '13-17',
  '18-24',
  '25-34',
  '35-44',
  '45-54',
  '55-64',
  '65+'
];

async function seedAudienceRanges() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true
    });
    console.log('Connected to database');

    for (const range of ranges) {
      // Upsert by range, audienceId generated by schema default
      const result = await Audience.findOneAndUpdate(
        { range },
        { range },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
      console.log(`Seeded audience range: ${result.range} (ID: ${result.audienceId})`);
    }

    console.log('Seeding complete');
  } catch (err) {
    console.error('Error seeding audience ranges:', err);
  } finally {
    await mongoose.disconnect();
    console.log('Disconnected from database');
  }
}

seedAudienceRanges();
